name: Deployment

on:
  pull_request:
    types: [ closed ]
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Sync
        env:
          dest: 'sunautob@93.125.99.120:/home/sunautob/test-lovelace/test_folder'
        run: |
          echo "${{secrets.SECRET}}" > deploy_key
          chmod 600 ./deploy_key
          rsync -chav \
            -e 'ssh -i ./deploy_key -o StrictHostKeyChecking=no' \
            --exclude /deploy_key \
            --exclude /.git/ \
            --exclude /.github/ \
            --exclude /node_modules/ \
            ./ ${{env.dest}}
