name: Deployment
on:
  pull_request:
    types: [ closed ]
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Sync
        env:
          dest: 'sunautob@93.125.99.120:/home/sunautob/test-lovelace/test_folder'
        run: |
          echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC2o2j/WpY+4jrrKVpVJkAXtpdGJedpgLriJZC3/RJOHB4nZvBgBC6iVxe824Qw0kXCcb1+RUaDt5Q5HRNytRSZRx/N1JAscehWRhK1PHeyhy94LUooYfEqjOUqpqvWBtuXsasZgIkq2Wg2aZN6jke1ihF8YAo0X5DwzUHQeS3063zwnkQpeVdPf6iDxfO92d1zfpjX5+K3VLmtzXfQcWcxSgZrWFUP0JCx9FmJot3Lri9ZHpDfEaDeFdCbBNBFrIZypLg8cNERze5GCWjt/BN7YFSZEo+5uJl5WU2vLuiKpOP5x5xbddhUtDQ0KRZs73WM84iy6awWxGDSk7vcru2B" > deploy_key
          chmod 600 ./deploy_key
          rsync -chav \
            -e 'ssh -i ./deploy_key -o StrictHostKeyChecking=no' \
            --exclude /deploy_key \
            --exclude /.git/ \
            --exclude /.github/ \
            --exclude /node_modules/ \
            ./ ${{env.dest}}
